---
title: "Article 1"
author:
  - name: Louise Lilin
    url: {}
date: 10-26-2020
output:
  distill::distill_article:
    self_contained: false
comments: true
---
# Article 1: Study Says Wild Crops Can Bolster Food Access in Arid Climates  

## I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT:

- Source of the article : [Food Tank](https://foodtank.com/news/2020/09/study-says-wild-crops-can-bolster-food-access-in-arid-climates/)  

- Publication date : 29 July 2020  

- Word count : 611 words

## II - VOCABULARY

| Word from the text | Synonym / Definition in English | Translation in French |
|:------------------:|:-------------------------------:|:---------------------:|
| Crop | Something cultivated | Culture |
| Sustainable | Something with time durability, causing little damage to the environment | Durable, viable |
| Indigenous | Native, local | Durable, viable |
| To bolster | To support | Soutenir |
| Drought | Lack of rain | Sécheresse |
| To flood | To fill up with water | Inonder |
| Yield | Amount produced | Récolte |
| Intercropping | Growing multiple crops in proximity | Culture intercalaire ou associée |
| Agrovoltaic | Combination of agriculture and photovoltaic power | Agrovoltaïque |


## III - ANALYSIS TABLE ABOUT THE STUDY

| Researchers | University of Arizona, Dr. Erin Riordan |
|---|---|
| Published in  | 29 July 2020  |
| General topic  |  Crop sustainability in arid environments (American desert) |
| Procedure / What was examined  |  Sustainability of different crops, conventional ones (like wheat, rice and soy) compared to indigenous ones (agaves, cacti, succulents and legumes) in an arid environment with a poor soil subjected to frequent droughts and floods, based on the requirements in terms of water, chemicals and energy.Benefits of the use of indigenous crops (ecosystems, health, working conditions). |
| Conclusion / discovery  | Indigenous crops are the more thriving in arid climates.The researchers also give guidelines to plant the crops and implement them in the local economy  |
| Remaining questions  | The indigenous crops will have some difficulty challenging the industry preferences for more conventional crops. The research team believes their results could be applied to other similar regions.  |

## IV - Article

Study Says Wild Crops Can Bolster Food Access in Arid Climates

A recent study from the University of Arizona finds wild desert **crops** could be the key to **sustainable** farming in arid conditions. The article, “An Aridamerican model for agriculture in a hotter, water scarce world,” proposes reintroducing **indigenous** food crops to desert regions **to bolster** food security, restore local ecosystems, and improve community health.

This summer, California’s Death Valley reached 130 degrees Fahrenheit—one of the hottest temperatures ever recorded on earth. Extreme weather events like heatwaves, **droughts**, and **floods** are only expected to worsen in the coming years, according to scientists at the United Nations, National Aeronautics and Space Administration, and National Oceanic and Atmospheric Administration.

These changes pose a threat to crops that grow hot, dry areas, such as “Aridamerica”—a desert region across the U.S. Southwest and Mexico, and the focus of the researchers’ recent study.

According to the study, many of the crops that grow in Aridamerica, including wheat, rice, and soy, are not naturally equipped to survive in arid climates, since they didn’t originate in the region. As temperatures rise and weather fluctuates, they will require more water, chemicals, and electricity to grow.

The study suggests that wild desert crops may be a sustainable alternative to conventional crops. Already adapted to extreme weather, these indigenous species require less water and energy, and produce more reliable **yields**.

“Wild desert plants have a remarkable number of adaptations to cope with heat, drought, unpredictable rainfall, and poor soils—the sorts of stressful growing conditions we are already seeing and expect to see more of in the future,” Dr. Erin Riordan, one of the study’s co-authors, tells Food Tank.

Riordan and her team evaluated plants traditionally eaten by Indigenous Sonoran Desert cultures. Their report highlights 17 crops most likely to thrive in arid climates and, in turn, benefit the health of local communities. The crops include an array of agaves, cacti, succulents, and legumes.

The researchers also provide guidelines on how to plant the crops. First, they propose **intercropping**, or strategically planting different crops side-by-side to maximize efficiency. For example, legume trees could provide shade for cacti and annuals, while their roots trap water and prevent soil erosion.

Intercropping isn’t new, Riordan tells Food Tank. “For centuries, traditional farming in Aridamerica has coupled perennial succulent plants like cacti and agaves, with annual species like amaranth.”

The team also suggests planting heat-sensitive crops in the shade of solar panels. This technique, known as **agrovoltaics**, combines agriculture with photovoltaic power, or solar power.

They note that desert plants can also provide locals with direct access to healthy food. According to the study, many indigenous crops are high in nutrients, including antioxidants and other cancer-preventing compounds. Some are shown to support heart health, kidney and immune system function, and insulin metabolism, which can help patients with type 2 diabetes.

The researchers also hope their sustainable farming model will benefit local communities by providing stable jobs and improving conditions for farm workers, since conventional crops will lower temperatures in the surrounding area.

Still, the Aridamerica model poses a number of challenges. “Industry preferences for commercial crops have eroded access to, and knowledge of, our regionally adapted wild foods,” Riordan tells Food Tank.

She says that marketing, seed-sharing networks, and partnerships with local chefs can help repopularize traditional desert ingredients. She also states that farmers might need financial incentives to switch from annual to perennial crops, which take longer to pay off.

If successful, the team believes their research can be adapted to other regions. “Today’s arid lands are our laboratories for the future,” says Riordan.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

{% if page.comments %}
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = https://llilin.github.io/llilin_blog/posts/2020-10-26-article-1/ ;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = article1; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://llilin.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endif %}
