---
title: "Article 4 - An AI Analysis of 500,000 Studies Shows How We Can End World Hunger"
author:
- name: Louise Lilin
  url: {}
date: "12-14-2020"
output:
  html_document:
    df_print: paged
  distill::distill_article:
    self_contained: no
comments: yes
---
## I - SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT :

Source of the article : https://earther.gizmodo.com/an-ai-analysis-of-500-000-studies-shows-how-we-can-end-1845346133

Word count : 1006

## II - VOCABULARY  

|Word from the text|Synonym/ definition|
|---|---|
|To outstrip|To exceed|
|Machine learning|Computer algorithms that improve automatically through experience|
|Off-the-shelf|Standard|
|Algorithm|Finite and well-defined sequence of instructions|
|White papers|Report that concisely informs about a complex issue, also providing ethical directions|
|Livestock|Farm animals|
|Technocratic approach|Approach in which experts in science and technological fields hold a lot of decisional power|

## III - ANALYSIS TABLE ABOUT THE STUDY


|Researchers|Ceres2030 researchers team|
|---|---|
|Published in ? when|Nature Food, Nature Plants and Nature sustainability, october 2020|
|General topic|Use of artificial intelligence to end world hunger|
|Procedure/ what was examined|Training of AI using machine learning to select useful data in over 500,000 scientific works / Analysis by the AI of selected literature, to point out solutions by comparing data : showing where money sould be targeted / Review of the results by the team for correction|
|Conclusions/ discovery|It would take $14 billions to end hunger in the world / farmers could cope with water stress by investing in livestock and data networks|
|Remaining questions|The algorithm still have to be improved / the study pointed out issues in the way studies are classified as well as some fields where to few studies have been conducted|


## IV - Article : An AI Analysis of 500,000 Studies Shows How We Can End World Hunger

Ending hunger is one of the top priorities of the United Nations this decade. Yet the world appears to be backsliding, with an uptick of 60 million people experiencing hunger in the last five years to an estimated 690 million worldwide.

To help turn this trend around, a team of 70 researchers published a landmark series of eight studies in Nature Food, Nature Plants, and Nature Sustainability on Monday. The scientists turned to machine learning to comb 500,000 studies and white papers chronicling the world’s food system. The results show that there are routes to address world hunger this decade, but also that there are also huge gaps in knowledge we need to fill to ensure those routes are equitable and don’t destroy the biosphere.

Despite the explosion of research, intractable problems like world hunger remain and are even growing worse in some cases. This is partly because new information is *outstripping* our ability to actually turn it into knowledge and wisdom. The great acceleration began in the 1700s and has gone into overdrive in the internet era; research shows a doubling of scientific citations over the past decade compared to a century rate of doubling in the 18th century. Using *machine learning* to analyze this rising mountain of information is one key way to make sense of it all.

Researchers with Ceres2030, a group of climate, social, and agricultural scientists and economists, are working to answer the question of how to meet the goal of ending hunger this decade. It’s one of the United Nations’ Sustainable Development Goals, a lofty set of ideals the world has so far failed to make any meaningful progress on. To help right the ship, the team at Ceres2030 enlisted artificial intelligence to see what research shows has been effective. Literature reviews can be a painstaking process that take months or even years to complete.

But after pulling a series of mostly *off-the-shelf* *algorithms*and training them for what to look for, the team unleashed them to analyze 500,000 pieces of literature on agricultural practices and development interventions to help improve yields or reduce hunger. It took a week for the machine learning to pare down the dataset of studies to those are actually useful.

Feeding in the data itself actually revealed a weakness in how research is classified. *White papers* and policy briefs—or what the scientists call “gray literature”—are often stashed on agency websites built in the dark ages of web development and “lack even basic features to select and download multiple citations,” according to the study. That alone points to the need to clean up the internet and make it so that all the information coming out is accessible, let alone useful.

The results, along with another analysis done by the UN Food and Agricultural Organization and German Center for Development Research, show that the world needs to kick in just $14 billion per year this decade to end hunger, double the current levels. For comparison, $14 billion is roughly 2% of what the U.S. spends on the military every year.

“The world produces enough food to feed everyone. So it’s unacceptable that 690 million people are undernourished, 2 billion don’t have regular access to sufficient amounts of safe, nutritious food, and 3 billion people cannot afford healthy diets,” Maximo Torero, the chief economist at FAO, said in a statement. “If rich countries double their aid commitments and help poor countries to prioritize, properly target and scale up cost effective interventions on agricultural R&D, technology, innovation, education, social protection and on trade facilitation, we can end hunger by 2030.”

The machine learning analysis shows where that money could be targeted to get the most out aid. For example, the findings show that more than three-quarters of smallholder farms are located in water-scarce areas. Those areas are likely to become more water-stressed in the future as the planet heats up. To help farmers cope, the machine learning analysis of the literature pointed to the value of investing in *livestock* and improving access to mobile phone data networks. The former can help improve productivity while the latter can help get weather forecasts and target when to apply fertilizer between rains to minimize runoff and waste.

Here, however, is where the human touch comes in. The researchers also found that while the machine learning analysis pointed to the benefits of these two interventions as targeted ways to reduce resource overuse and provide a layer of diversity in income, there were gaps. Many of the studies dredged up by artificial intelligence failed to include key variables such as gender and, until the past decade, few looked at the environmental impacts. In a world where women make up 43% of farmers and agricultural laborers, but bear disproportionate burdens when it comes to work and the amount of land they own or work, looking at interventions that can specifically help women is of utmost importance to ending hunger as well as meeting other Sustainable Development Goals like ending poverty (the first goal) and reaching gender equality (the fifth goal).

The analysis also shows that many previous studies have largely focused on crop yields rather than improving human well-being, which is a much more holistic—and I’d argue, more important—metric of success. Few studies have taken into account nutrition, a metric crop yield completely misses, or how to prepare farmers for future climate change. Those areas require more research and fast if investments to end hunger are to be spent wisely.

Other groups have also put forward ideas for how to balance well-being and the planet through fixes to our diets, food waste, and the agriculture system, notably last year’s EAT-Lancet report. The results of all this work, but particularly the new machine learning analysis point to how much work is left to be done and why a *technocratic approach* alone won’t cut it.


